// <auto-generated />
using BusinessesApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BusinessesApi.Migrations
{
    [DbContext(typeof(BusinessesApiContext))]
    [Migration("20200403233524_FinalMigration")]
    partial class FinalMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BusinessesApi.Models.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("BusinessId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            BusinessId = 1,
                            Description = "Italian Restaurant",
                            Name = "Piazza Italia"
                        },
                        new
                        {
                            BusinessId = 2,
                            Description = "Department store",
                            Name = "Nordstrom"
                        },
                        new
                        {
                            BusinessId = 3,
                            Description = "Grocery store",
                            Name = "New Seasons"
                        },
                        new
                        {
                            BusinessId = 4,
                            Description = "Caffee",
                            Name = "Umbria"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
